blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.post_list, name='blog'),
    path('<slug:post_slug>/', views.post_detail, name='post_detail'),
    path('<slug:post_slug>/<int:comment_id>/', views.reply_comment, name='reply_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:reply_id>', views.delete_reply, name='delete_reply'),
    path('<int:comment_id>', views.delete_comment, name='delete_comment'),
    
    ]

credible_reviews/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('companies/', include('companies.urls')),
    path('companyusers/', include('companyusers.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from .import Int_max
from companies.models import Company
from companyusers.models import UserProfileCompany


class UserProfile(models.Model):    
    Abuja = 'Abuja'
    Abia = 'Abia'
    Adamawa = 'Adamawa'
    Akwa_Ibom = 'Akwa Ibom'
    Anambra	= 'Anambra'
    Bauchi = 'Bauchi'
    Bayelsa = 'Bayelsa'
    Benue = 'Benue'
    Borno = 'Borno'
    Cross_River	= 'Cross River'
    Delta = 'Delta'
    Ebonyi = 'Ebonyi'
    Edo = 'Edo'
    Ekiti = 'Ekiti'
    Enugu = 'Enugu'
    Gombe = 'Gombe'
    Imo = 'Imo'
    Jigawa = 'Jigawa'
    Kaduna = 'Kaduna'
    Kano = 'Kano'
    Katsina = 'Katsina'
    Kebbi = 'Kebbi'
    Kogi = 'Kogi'
    Kwara = 'Kwara'
    Lagos = 'Lagos'
    Nasarawa = 'Nasarawa'
    Niger = 'Niger'
    Ogun = 'Ogun'
    Ondo = 'Ondo'
    Osun = 'Osun'
    Oyo = 'Ibadan'
    Plateau = 'Plateau'
    Rivers = 'Rivers'
    Sokoto = 'Sokoto'
    Taraba = 'Taraba'
    Yobe = 'Yobe'
    Zamfara = 'Zamfara'

    state = [
        (Abuja, 'Abuja'),
        (Abia, 'Abia'),	
        (Adamawa, 'Adamawa'),	
        (Akwa_Ibom, 'Akwa Ibom'),
        (Anambra, 'Anambra'),
        (Bauchi, 'Bauchi'),
        (Bayelsa, 'Bayelsa'),
        (Benue,	'Benue'),
        (Borno, 'Borno'),
        (Cross_River, 'Cross River'),
        (Delta, 'Delta'),
        (Ebonyi, 'Ebonyi'),
        (Edo, 'Edo'),
        (Ekiti, 'Ekiti'),
        (Enugu, 'Enugu'),
        (Gombe, 'Gombe'),
        (Imo, 'Imo'),
        (Jigawa, 'Jigawa'),
        (Kaduna, 'Kaduna'),
        (Kano, 'Kano'),
        (Katsina, 'Katsina'),
        (Kebbi, 'Kebbi'),
        (Kogi, 'Kogi'),
        (Kwara, 'Kwara'),
        (Lagos, 'Lagos'),
        (Nasarawa, 'Nasarawa'),
        (Niger, 'Niger'),
        (Ogun, 'Ogun'),
        (Ondo, 'Ondo'),
        (Osun, 'Osun'),
        (Oyo, 'Ibadan'),
        (Plateau, 'Plateau'),
        (Rivers, 'Rivers'),
        (Sokoto, 'Sokoto'),
        (Taraba, 'Taraba'),
        (Yobe, 'Yobe'),
        (Zamfara, 'Zamfara')
    ]
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics', default='/company_logo/pic.jpg')
    location = models.CharField(max_length=30, choices=state, default=Lagos)
    phone = models.CharField(max_length=30, blank=True, null=True)
    

    def __str__(self):
        return self.user.username

class GenericReview(models.Model):
    merchant = 'online merchant'
    forex = 'forex company'
    betting = 'sports betting'
    fooddrug = 'food and drug'
    education = 'education'
    transportation = 'transportation'
    logistics = 'logistics'
    hospitality = 'hospitality'
    healthcare = 'health'
    construction = 'construction'
    handle = 'social media handle'
    blog = 'blog'
    finance = 'finance'
    media = 'media'
    agency = 'governement agency'
    other = 'other'
    manufacturing = 'manufacturing'
    sector = [
        (merchant, 'Online Merchant'),
        (forex, 'Forex Company'),
        (betting, 'Sports Betting'),
        (fooddrug, 'Food and Drug'),
        (education, 'Education'),
        (transportation, 'Transportation'),
        (logistics, 'Logistics'),
        (hospitality, 'Hospitality'),
        (healthcare, 'Healthcare'),
        (construction, 'Construction'),
        (blog, 'Blog'),
        (handle, 'Social Media Handle'),
        (finance, 'Finance'),
        (media, 'Media'),
        (manufacturing, 'Manufacturing'),
        (agency, 'Governement Agency'),
        (other, 'Other')
    ]
    Abuja = 'Abuja'
    Abia = 'Abia'
    Adamawa = 'Adamawa'
    Akwa_Ibom = 'Akwa Ibom'
    Anambra	= 'Anambra'
    Bauchi = 'Bauchi'
    Bayelsa = 'Bayelsa'
    Benue = 'Benue'
    Borno = 'Borno'
    Cross_River	= 'Cross River'
    Delta = 'Delta'
    Ebonyi = 'Ebonyi'
    Edo = 'Edo'
    Ekiti = 'Ekiti'
    Enugu = 'Enugu'
    Gombe = 'Gombe'
    Imo = 'Imo'
    Jigawa = 'Jigawa'
    Kaduna = 'Kaduna'
    Kano = 'Kano'
    Katsina = 'Katsina'
    Kebbi = 'Kebbi'
    Kogi = 'Kogi'
    Kwara = 'Kwara'
    Lagos = 'Lagos'
    Nasarawa = 'Nasarawa'
    Niger = 'Niger'
    Ogun = 'Ogun'
    Ondo = 'Ondo'
    Osun = 'Osun'
    Oyo = 'Ibadan'
    Plateau = 'Plateau'
    Rivers = 'Rivers'
    Sokoto = 'Sokoto'
    Taraba = 'Taraba'
    Yobe = 'Yobe'
    Zamfara = 'Zamfara'

    state = [
        (Abuja, 'Abuja'),
        (Abia, 'Abia'),	
        (Adamawa, 'Adamawa'),	
        (Akwa_Ibom, 'Akwa Ibom'),
        (Anambra, 'Anambra'),
        (Bauchi, 'Bauchi'),
        (Bayelsa, 'Bayelsa'),
        (Benue,	'Benue'),
        (Borno, 'Borno'),
        (Cross_River, 'Cross River'),
        (Delta, 'Delta'),
        (Ebonyi, 'Ebonyi'),
        (Edo, 'Edo'),
        (Ekiti, 'Ekiti'),
        (Enugu, 'Enugu'),
        (Gombe, 'Gombe'),
        (Imo, 'Imo'),
        (Jigawa, 'Jigawa'),
        (Kaduna, 'Kaduna'),
        (Kano, 'Kano'),
        (Katsina, 'Katsina'),
        (Kebbi, 'Kebbi'),
        (Kogi, 'Kogi'),
        (Kwara, 'Kwara'),
        (Lagos, 'Lagos'),
        (Nasarawa, 'Nasarawa'),
        (Niger, 'Niger'),
        (Ogun, 'Ogun'),
        (Ondo, 'Ondo'),
        (Osun, 'Osun'),
        (Oyo, 'Ibadan'),
        (Plateau, 'Plateau'),
        (Rivers, 'Rivers'),
        (Sokoto, 'Sokoto'),
        (Taraba, 'Taraba'),
        (Yobe, 'Yobe'),
        (Zamfara, 'Zamfara')
    ]
    user_g = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name_g = models.CharField(max_length=250, verbose_name='Name of Company:')
    company_logo_g = models.ImageField(upload_to='generic_logos', default='/company_logo/pic.jpg', verbose_name='Company Logo:')
    picture_evidence_g = models.ImageField(upload_to='evidence', default='/company_logo/pic.jpg', verbose_name='Upload Proof:')
    company_sector_g = models.CharField(max_length=30, choices=sector, default=merchant, verbose_name='Sector')
    company_state_g = models.CharField(max_length=30, choices=state, default=Lagos, verbose_name='State')
    company_address_g = models.TextField(max_length=2000, verbose_name='Company Address:')
    company_website_g = models.CharField(max_length=500, blank=True, null=True, verbose_name='Website:')
    company_email_g = models.EmailField(max_length=500, blank=True, null=True, verbose_name='Company Email:')
    company_phone_g = models.CharField(max_length=500, verbose_name='Company Phone:')
    subject_g = models.CharField(max_length=100, verbose_name='Subject:')
    review_text_g = models.TextField(max_length=500, verbose_name='Your Review:')
    rating_g = Int_max.IntegerRangeField(min_value=1, max_value=5, verbose_name='Your Rating:')
    date_added_g = models.DateField('Review Date', auto_now_add=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.review_text_g


class Review(models.Model):
    # CASCADE ensures that when a company is deleted, their reviews remains
    company = models.ForeignKey(Company, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # SET_NULL ensures that when a user is deleted, their reviews get deleted too
    subject = models.CharField(max_length=100)
    review_text = models.TextField(max_length=500, verbose_name='Your Review:')
    rating = Int_max.IntegerRangeField(min_value=1, max_value=5)
    date_added = models.DateField('Review Date', auto_now_add=True)
    verified = models.BooleanField(default=False)
    def __str__(self):
        return self.review_text

class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    response = models.TextField(max_length=200, verbose_name='Your Response')
    date_added = models.DateField('Response Date', auto_now_add=True)

    def __str__(self):
        return self.response

class ResponseReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    reply = models.TextField(max_length=200, verbose_name='Your Response')
    date_added = models.DateField('Response Date', auto_now_add=True)

    def __str__(self):
        return self.reply

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

class Flag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    flag_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

templates/browse_review.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% static 'images' as baseURL %}
{% load crispy_forms_tags %}



{% block filter %}
        
        <div class="container-fluid border-0 text-justify">
        <div class="row" id="tm-filter-button-div">
            <span class="font-weight-bold py-1 mx-auto text-info">
                <button id="tm-form-filter-button" class="btn btn-sm btn-outline-primary font-weight-bold">Click to Filter Reviews</button>
            </span>
        </div>
        <div class="row" id="tm-form-filter">
            <span class="font-weight-bold py-1 mx-auto text-info">
                <form action="" method="GET" id="tm-filter-form">
                
                    <div class="row ">
                                                    
                        <div class="col-md-4">
                            {{ filtered_reviews.form.company|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ filtered_reviews.form.rating|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ filtered_reviews.form.date_added|as_crispy_field }}
                        </div>
                        
                        <div class="col-md-1">
                            <div></div>
                            <input class="btn btn-sm font-weight-bold btn-info mt-4" type="submit" value="Filter">
                        </div>
                        <br>
                        <div class="col-md-1">
                            <a href="{{request.META.HTTP_REFERER}}"><input class="btn btn-sm font-weight-bold btn-info mt-4" type="button" value="Back"></a>
                        </div>


                    </div>
                    <div class="row mt-1 ">
                                                    
                        <div id="company_div" class="hide_form pointerchange col-md-12">
                            click here to get ID then filter: <span class="numberbg" id="company_name"></span>
                        </div>
                        


                    </div>
                    
                
                
            </form>
            </span>
        </div>
{% endblock filter %}
{% block featuredcomp %}
                <div class="col-md-10 ">
                <div class="row  container-fluid border-0 ">
                        <div class="col-md py-2 text-center">
                            <p class="font-weight-bold">
                            <a class="text-decoration-none" href="{% url 'contact' %}">Contact Us </a> if you feel the review is against our ethic and <a href="{% url 'privacy-terms' %}"> terms of use</a>. <br>
                            {% for error in messages %}
                                    <span class="text-danger">{{ error }}</span>
                                {% endfor %}
                            </P> 
                        </div>
                        
                </div> 
                    
                        
                                            
                <div class=" container-fluid bg-light ">
                    <div class="card border-0 bg-light py-2 text-center">

                        <div class="row ">
                            {% comment %} without .qs extension, the returned value won't be an iterable hence a for loop can't be used on it {% endcomment %}
                            
                            {% for review in page %}
                            <div class=" single_review_div col-md-3 px-2 py-2">
                                            <div  class="col-md text-wrap ">
                                                <h6 style="font-size:x-small;" class="font-weight-bold borderrounded navbarbg px-1 py-1"> <img src="{{review.user.userprofile.profile_picture.url}}" alt="profile_pic" width="30" height="30" class="rounded-circle"> &nbsp; 
                                                    {% for item in "12345"|make_list %}
                                                    <span style="font-size: large;" class="fa fa-star {% if forloop.counter <= review.rating %}checked{% endif %}"></span>
                                                    {% endfor %}
                                                <br>
                                                
                                                    
                                                
                                                {{review.user.first_name }} Reviewed: {{review.company}} &nbsp; <span style="font-size: small; font-family: 'Courier New', monospace;" class="justify-content-end"> <i style="color: darkorange;" class="fas  fa-heart"></i> <span class="numberbg"> {{review.like_set.all.count}} </span> </span></h6>
                                                <p class="text-center mx-1"><span class="font-weight-bold">{{review.subject}}</span> <br>
                                                
                                                {{review.review_text}}
                                                    
                                                    
                                                </p>
                                            
                                            <div class="row ">
                                                {% if request.user.is_authenticated and request.user|has_group:"regular" %}
                                                    <div class="row  px-1  mx-1">

                                                        <div class="row px-4">
                                                        <div class="col-md-4 ">
                                                            <a href="{% url 'likes' review.id %}"><i  id="tooltip" class="btn btn-sm fas fa-thumbs-up "></i></a>
                                                        </div>
                                                        <div class="col-md-4 ">
                                                            <a href="#"><i  id="" class="btn btn-sm fas fa-exclamation-triangle likefont"></i></a> 
                                                        </div>
                                                        <div class="col-md-4 ">
                                                            <i  class=" share_button btn btn-sm fas fa-share-alt likefont"></i> 
                                                        </div>
                                                        </div>
                                                        <div class="row px-5">
                                                            <div style="font-size: larger;" class="social_share formhidden col-md mt-2 font-weight-bold"><i style="color: #3b5998;" class="fab fa-facebook-f mr-3"></i><i style="color: #e1306c;" class="fab fa-instagram mr-3"></i><i style="color: #1da1f2;" class="fab fa-twitter mr-3"></i><i style="color: #25d366;" class="fab fa-whatsapp"></i></div>
                                                        </div>
                                                    </div>
                                                        
                                                {% elif request.user.is_authenticated and request.user|has_group:"company"%}
                                                    <div class="row px-1 mx-2 ">
                                                        <span style="font-size: x-small; color:darkred; font-weight:800;">Company users can't like Reviews.</span>
                                                    </div>
                                                      
                                                {% else %}
                                                    <div class="row px-1 mx-2">
                                                        <span style="font-size: x-small; color:darkred; font-weight:800;">Please Login as Regular User to Like Reviews.</span>
                                                    </div>
                                                     
                                                {% endif %}<br> 
                                                   
                                                <div class="col-md">
                                                   <br> 
                                                    <span id="tooltiptext">Click to Like Review</span>
                                                </div>
                                            </div>
                                
                                        </div>
                                    </div>
                            {% empty %}
                                <div class="card border mr-2 text-danger font-weight-bold" style="width: 100%; height: 100%">
                                    
                                        <p> ooops! No Review with such details, please modify your search...</p>
                                    
                                </div>
                        </div>
                            {% endfor %} 
                            
                                                    
                        </div>
                        <hr>
                        <div class="row text-center">
                            {% if page.has_previous%}
                            <div class="col-md-2">
                                <a  href="{% url 'browse_review' %}?page={{page.previous_page_number}}"> <i style="font-size: xx-large;" class="fas fa-angle-double-left"></i> </a>
                            </div>
                            {% endif %}
                            
                            <div  class="col-md-8 font-weight-bold">
                            <ul style="list-style-type: none;">
                                
                            {% for l in  page.paginator.page_range %}
                            {% if forloop.counter <= 10 %}
                            <li style="display: inline-block; padding: 0 3px 0 0;"><a style="text-decoration: none;" href="?{% param_replace page=forloop.counter %}">{{forloop.counter}}</a></li>
                            {% endif %}
                            {% endfor %}
                            </ul>
                            </div>
                            {% if page.has_next %}
                            
                            
                            <div class="col-md-2">
                                <a href="{% url 'browse_review' %}?page={{page.next_page_number}}"> <i style="font-size: xx-large;" class="fas fa-angle-double-right"></i> </a>
                            </div>
                            {% endif %}
                        </div>
                        
                        
                
                    </div>
            </div>
{% endblock featuredcomp %}

{% block article %}
<article class="mt-2 bg-white mx-2">
    
    
</article>
{% endblock article %}

{% block browse_review_script %}
    <script>
        $(document).ready(function () {
            var company_div = $('#company_div');
            var company_name = $('#company_name');
            var company = $('#id_company');
            company.keyup(function(){
                company_div.removeClass('hide_form', {duration:500});
                $.ajax({
                    type: "GET",
                    url: "{% url 'browse_review' %}",
                    data: {
                        'search_text': $(this).val()
                          },
                    dataType: 'json',
                    success: gotcompany,
                    
                });
            function gotcompany(data, textStatus, jqXHR){
                console.log(data);
                company_name.text(data['name']);
                company_div.click(function(){
                    company.val(data['id']);
                })
            }
            });
        });
        
    </script>   

{% endblock browse_review_script %}

templates/cr-seal.html
{% extends 'base.html' %}

templates/disclaimer.html
{% extends 'base.html' %}


            
{% block blockslideshow %}
    <div class="col-md-7 py-2 ">
        <h1 class="h4 borderrounded font-weight-bold navbarbg  px-2 py-2 text-center"> Disclaimer </h1>
        <p class="px-2"><a href="{% url 'index' %}">Credible Reviews</a> encourages Nigerian residents/visitors to share their experiences. We mainly operate on an honor system, meaning that we believe people who send in reviews to be published do so with the intention of making other Nigerians aware. We will try our very best to verify the information provided to us, however, we accept no liability for the content posted as these are opinions of our viewers.

        We also encourage people to rate a business and share their personal experiences via the comments box. Our goal eventually is to have a good number of people talking about a specific review and rating a business, so others don’t have to rely on just one side of a story (but if everyone’s saying the same or similar things about a particular place then chances are that the place is really what it seems).

        If something doesn’t seem quite right about a specific review, please reach out to us with your concerns. We’d love to hear from you!</p>
    <!-- Slide show ends-->
    </div>
{% endblock blockslideshow %}

templates/done.html
{% extends 'base.html' %}

{% block section %}  
        <section class="mt-2 bg-white mx-2">
            
            <div class="container-fluid border-0 text-justify">
                <div class="row">
                    <span class="font-weight-bold px-2 py-1 mx-auto text-danger">...Created with<span class="h3"> &hearts;</span> because we believe that behind every review, there is a heartfelt experience...</span>
                </div>
                <div class="row">
                    
                        <div class="tm-nav navbar-expand-lg col-md-2  navbar-light bg-light py-2">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                              </button>
                            <div class=" collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class=" nav  flex-column">
                                
                                <li class="nav-item">
                                    <a   class="nav-link active font-weight-bold" href=" {% url 'index' %} ">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a    class="nav-link font-weight-bold" href=" {% url 'about' %} ">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a    class="nav-link font-weight-bold" href="{% url 'submit_review' %}">Submit Review</a>
                                </li>
                                <li class="nav-item">
                                    <a   class="nav-link font-weight-bold" href=" {% url 'browse_review' %} ">Browse Review</a>
                                </li>
                                
                                <li class="nav-item ">
                                    <a    class="nav-link font-weight-bold" href=" {% url 'cr-seal' %}">API Coming Soon</a>
                                </li>
                                <li class="nav-item">
                                    <a    class="nav-link font-weight-bold" href=" {% url 'featured-companies' %}">Featured Companies</a>
                                </li>
                                <li class="nav-item">
                                    <a   class="nav-link font-weight-bold" href=" {% url 'faq' %}">FAQ</a>
                                </li>
                                
                            </ul>
                        </div>
                        </div>
                    
                    
                  
                    <div class="col-md-7 py-2 ">
                        <h1 class="h4 font-weight-bold bg-primary text-white px-2 py-2 text-center"> Registration Form Submitted</h1>
                        <p class="text-wrap"> Your registration form have been successfully submitted kindly visit your email to activate your account and enjoy the full features of Credible Reviews!. 
                            <br/> <span style="font: bold;" >Your experience and satisfaction mean the world to our team!!</span>
                        </p>
                    </div>
                <div class="col-md-3 py-2">
                    <h2 class="h5 px-2 py-2 text-center bg-primary text-white">Advertise here... Get noticed!</h2>
						<!-- Slideshow advert container -->
                        <div class="galleryContaineradvert">
                            <div class="slideShowContaineradvert">
                                <div id="playPauseadvert" onclick="playPauseSlidesadvert()"></div>
                                <div onclick="plusSlidesadvert(-1)" class="nextPrevBtnadvert leftArrowadvert"><span class="arrowadvert arrowLeftadvert"></span></div>
                                <div onclick="plusSlidesadvert(1)" class="nextPrevBtnadvert rightArrowadvert"><span class="arrowadvert arrowRightadvert"></span></div>
                                <div class="captionTextHolderadvert"><p class="captionTextadvert slideTextFromTopadvert"></p></div>
                                <div class="imageHolderadvert">
                                    <img src="/static/slide_images_advert/img_1.jpg"><!-- image resolution should be - 1366X768-->
                                    <p class="captionTextadvert">lo Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                </div>
                                <div class="imageHolderadvert">
                                    <img src="/static/slide_images_advert/img_2.jpg">
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                </div>
                                <div class="imageHolderadvert">
                                    <img src="/static/slide_images_advert/img_3.jpg">
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                </div>
                                <div class="imageHolderadvert">
                                    <img src="/static/slide_images_advert/img_4.jpg">
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                    <p class="captionTextadvert">Welcome to Credible Reviews Adverts You are here either becasue you </p>
                                </div>
                            
                        </div>
                        <div id="dotsContaineradvert"></div>
                    </div>
                <!-- Slide show advert ends-->                  
                </div>
            </div>
            
        </section>
        {% endblock section %}

templates/general-user.html
{% extends 'base.html' %}

templates/user_page.html
{% extends 'base.html' %}

templates/validate-business.html
{% extends 'base.html' %}